### ISSUE TITLE
MacOSX用の配布バイナリを追加する

### ISSUE THREAD

**Issue by sizuhiko** [chirimen-oh/CHIRIMEN-tools#1]
元の議論issue:
https://github.com/chirimen-oh/any-issues/issues/59

`Mac_OS_X` フォルダを作り、以下のコンパイル済みバイナリを入れる
- [rkflashtool](https://github.com/linux-rockchip/rkflashtool)
- [rkunpack](https://github.com/naobsd/rkutils)
## TODO

手順のドキュメントは別のissue?

**Comment by gurezo** [comment]
[chirimen-oh.github.io](https://github.com/chirimen-oh/chirimen-oh.github.io) に issue を立てて、
このissue をリンクしておけば、良いかと思います。

**Comment by sizuhiko** [comment]
元スレのURLを入れているので、any-issueの関連issueからはリンクされています！

**Comment by gurezo** [comment]
merge したので、close
